sudo: required
services:
  - docker
notifications:
  email: false
install:
- false
script:
- true
deploy:
- provider: script
  script: bash ./script/push-image
  on:
    repo: bakins/nginx-php-grpc
    branch: master

