web:
  image: nginx:1.15
  ports:
  - "8080:80"
  volumes:
  - ./app:/app
  - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
  - php
php:
  image: bakins/php-grpc:latest
  volumes:
  - ./app:/app
